FROM node:22-alpine AS build
ARG VITE_API_URL=http://localhost:5200
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN VITE_API_URL=$VITE_API_URL npm run build

FROM nginx:1.27-alpine AS runtime
WORKDIR /usr/share/nginx/html

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]