services:
  backend:
    build:
      context: ./backend
    container_name: orbitboard-backend
    ports:
      - "5200:5200"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5200

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5200
    container_name: orbitboard-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
